### ISSUE TITLE
download/update background genome database (from GISAID for our own runs, or Nextstrain/Genbank)

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#26]
We can pull in existing scripts from the `opendata` branch of CoVizu

**Comment by ArtPoon** [comment]
Debugging `retrieve-nsgb.py` - for some reason it is only outputting insertions and deletions.

**Comment by ArtPoon** [comment]
To stop spamming the Nextstrain team with requests for the metadata file, download a local copy and run script with a `file://` address instead of the URL, *e.g.*, `python3 scripts/retrieve-nsgb.py opendata.json -t 2 --limit 100 --metaurl file:///Users/art/git/gromstole/data/metadata.tsv.gz`

**Comment by ArtPoon** [comment]
The problem was that the input does not have quality scores.

**Comment by ArtPoon** [comment]
Example output:
```json
{
  "B": {
    "mutations": {
      "~|3777|G": 1,
      "~|8387|G": 1,
      "~|8986|A": 1,
      "~|6967|A": 1,
      "~|11763|A": 1,
      "~|21315|A": 1,
      "~|24324|G": 2,
      "~|7015|A": 1,
      "~|21136|G": 1,
      "~|8000|C": 1,
      "~|9533|T": 1,
      "~|103|A": 1,
      "~|110|C": 1,
      "~|111|G": 1,
      "~|118|G": 1,
      "~|119|C": 1,
      "~|123|A": 1,
      "~|6995|C": 1,
      "~|11082|T": 3,
      "~|14804|T": 3,
      "~|17246|C": 3,
      "~|26143|T": 3
    },
    "count": 20
  },
  "A": {
    "mutations": {
      "~|8781|T": 2,
      "~|28143|C": 2,
      "~|4945|C": 1
    },
    "count": 2
  },
```

**Comment by DBecker7** [comment]
Well this explains why my code wasn't giving me a lot of mutations when I used NSGB data. Thanks for fixing this, @ArtPoon!
