### ISSUE TITLE
compare mutation set to background database to determine lineage-defining mutations

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#28]

**Comment by ArtPoon** [comment]
This is basically implemented - we need to expand this to handle curated constellations, however (also see #27)

**Comment by DBecker7** [comment]
@ArtPoon by curated constellations, do you mean the ones [like this](https://github.com/cov-lineages/constellations/tree/main/constellations/definitions)? If so, is there an easy way to convert something like ["nsp3:L741F"](https://github.com/cov-lineages/constellations/blob/main/constellations/definitions/cA.23.1%2BE484K.json) to match the mutation labels output by `minimap2` or `SC2Locator`? I've failed to figure this out in the past.

**Comment by ArtPoon** [comment]
Yeah I'm writing a new issue on exactly this problem - amino acid substitutions are frustratingly ambiguous at the nucleotide level.

**Comment by ArtPoon** [comment]
#36
