### ISSUE TITLE
Report mutation counts and coverage

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#37]
* @ebrintn had implemented an RMarkdown script for drawing a heatmap/table of mutation counts
<img width="500" alt="Screen Shot 2022-01-18 at 3 08 58 PM" src="https://user-images.githubusercontent.com/1109328/150010926-a1171b18-84ff-43ce-bf5f-7830eeb9116f.png">

* we also have an R script for drawing coverage plots, but those might not be getting generated now:
![image](https://user-images.githubusercontent.com/1109328/150010743-14c0940d-fc30-4280-8a45-9f9b8b7489bb.png)

**Comment by ArtPoon** [comment]
The tables can be derived from the JSON file produced by `estimate-freq.R`

**Comment by ArtPoon** [comment]
We should start reporting both BA.1 and BA.2

**Comment by ebrintn** [comment]
> We should start reporting both BA.1 and BA.2

Should the Rmarkdown file be modified accordingly? If so, I will take some time to do that.

**Comment by ArtPoon** [comment]
I think we are adapting the Rmd file to just generate visualizations, such as your tables
I'd rather figure out the outputs before we start issuing full reports again

**Comment by ebrintn** [comment]
> I think we are adapting the Rmd file to just generate visualizations, such as your tables I'd rather figure out the outputs before we start issuing full reports again

Sounds good.
