### ISSUE TITLE
Error in profile.glm: profiling has found a better solution

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#43]
This came up while processing one of the recent runs for constellation B.1.617.2:
```R
Error in profile.glm(object, which = parm, alpha = (1 - level)/4, trace = trace) : 
  profiling has found a better solution, so original fit had not converged
Calls: suppressMessages ... tryCatchList -> confint -> confint.glm -> profile -> profile.glm
Execution halted
```

**Comment by ArtPoon** [comment]
This came up in `estimate-freqs.R`, lines 293-312 where we're fitting the quasibinomial model to count and coverage data for each sample.  There was an especially bad sample:
```R
> y
 [1] NA NA NA  1 NA NA  1 NA NA NA NA NA NA
> n
 [1] 0 0 0 1 0 0 1 0 0 0 0 0 0
```

**Comment by GopiGugan** [comment]
Ran into this issue again:

```R
> y
 [1] NA NA NA NA NA NA NA  1 NA NA  5  1 NA
> n
 [1] 0 0 0 0 0 0 0 1 0 0 5 1 0
```

**Comment by ArtPoon** [comment]
Beh - what if you change the following to `<=3`?
https://github.com/PoonLab/gromstole/blob/b11c374eb80527e1246a5302abd1a2c7cc60627f/scripts/estimate-freqs.R#L296

**Comment by ArtPoon** [comment]
`confint` fails when the estimated frequency is 0 or 1.  This appears to be a numerical precision issue:
```R
> probs[i]
[1] 1
> probs[i]-1
[1] -8.654633e-12
> probs[i]>1
[1] FALSE
> probs[i]<1
[1] TRUE
> probs[i]==1
[1] FALSE
```
I've modified the condition to include estimates that are too close to 1:
```R
  if (sum(is.na(y)) < length(y)-1 & 
      !is.na(probs[i]) & 
      (probs[i] >= 1e-5 & probs[i] <= 1-(1e-5)) ) {
    suppressMessages(ci <- tryCatch(confint(fit)))
    lo[i] <- exp(ci[1]) / (1+exp(ci[1]))
    hi[i] <- exp(ci[2]) / (1+exp(ci[2]))
  }
```
