### ISSUE TITLE
Running viralrecon

### ISSUE THREAD

**Issue by Abayomi-Olabode** [PoonLab/gromstole#45]
Everything should be already set up on Langley -- nextflow, docker

- Run requirements

Samplesheet.csv for each upload consisting 3 columns "sample,fastq_1,fastq_2"

A python file that creates this file ```create_samplesheet_modified.py``` can be found in ```/home/abayomi/viralrecon```

- Command line

```
nextflow run nf-core/viralrecon -r 2.3 --platform illumina --protocol amplicon --input ./samplesheet.csv --genome 'MN908947.3' --primer_set artic --primer_set_version 3 --max_time 12.h --max_cpus 4 --max_memory 5GB --skip_assembly --skip_kraken2 -profile docker
```

**Comment by ArtPoon** [comment]
We just need scripts to:
1. Convert the `.tsv` outputs to the same format as gromstole
2. Extract coverage per site from the BAM files

**Comment by ArtPoon** [comment]
Labs may be using ARTIC primer sets v3 or v4, we need to use this information for the primer trimming step (will vary among runs)

**Comment by Abayomi-Olabode** [comment]
```indexing bam files```
- samtools index sample_1.sorted.bam
- samtools index sample_1.ivar_trim.sorted.bam

```samtools coverage depth```
- samtools depth sample_1.sorted.bam > sample_1.samdepth.bed
- samtools depth sample_1.ivar_trim.sorted.bam > sample_1.ivar.samdepth.bed

```mosdepth coverage depth```
- mosdepth sample_1.ivar.mosdepth mosdepth sample_1.ivar_trim.sorted.bam
- mosdepth sample_1.ivar.mosdepth sample_1.ivar_trim.sorted.bam 

```bedtools coverage depth```
- bedtools genomecov -d -ibam sample_1.sorted.bam > sample_1.beddepth.bed
- bedtools genomecov -d -ibam sample_1.ivar_trim.sorted.bam > sample_1.ivar.bed

```or```
- genomeCoverageBed -d -ibam sample_1.sorted.bam > sample_1.gendepth.bed
- genomeCoverageBed -d -ibam sample_1.ivar_trim.sorted.bam > sample_1.ivar.gendepth.bed

**Comment by Abayomi-Olabode** [comment]
Moving ahead with ```bedtools``` while I keep troubleshooting.
