### ISSUE TITLE
estimate-freqs error

### ISSUE THREAD

**Issue by suskraem** [PoonLab/gromstole#46]
Hello,
I found that some constellation files give the following error when running the estimate-freq script: 
Error in pos[i] <- start_pos + (codon - 1) * 3 : 
  replacement has length zero
Problematic files are: 
cP.2, cB.1.617.3, cB.1.617.1, cB.1.525, cB.1.351, cB.1.1.7, cB.1.1.7+E484K, cA.23.1+E484K,cA.23.1,cB.1.1.318

I attached an example mapped file to reproduce the error and am running the following loop:
for i in constellations/definitions/*.json; do name=$(basename -- "$i"); name2=${name%%.json}; echo $name2; Rscript scripts/estimate-freqs.R error_test $i $name2.json; done

[error_test.zip](https://github.com/PoonLab/gromstole/files/8050899/error_test.zip)

Thanks for your help!
Susanne

**Comment by ArtPoon** [comment]
@GopiGugan can you please check this out?

**Comment by ArtPoon** [comment]
since those are constellations we haven't actually run locally, I suspect the problem is being caused by inconsistent notation in those JSON files

**Comment by ArtPoon** [comment]
Is there a solution already implemented in scorpio?
https://github.com/cov-lineages/scorpio/blob/2ae9e99b8c638786a6a5867222057c5b1ac28712/scorpio/scripts/type_constellations.py#L122

**Comment by ArtPoon** [comment]
Since we are mapping nucleotide changes to ORF1ab, we need to map nsp-level substitution labels to this same coordinate system
