### ISSUE TITLE
Determine why some samples have high frequencies of both BA.1 and BA.2 that sum >100%

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#53]
This may be due to a small number of shared mutations between the BA.1 and BA.2 constellations.
* Locate some Western samples that are apparently affected by this issue
* Examine mutation frequencies

**Comment by Abayomi-Olabode** [comment]
These 3 prevalent mutations, shared between ```BA.1``` and ```BA.2``` seem to be driving the frequencies. We need to find a way to account for shared mutations when calling variants and computing frequencies.

```
spike:Q493R
nuc:C25000T
nuc:C25584T
```

**Comment by ArtPoon** [comment]
We should fork the constellations repository and then point our submodule to our fork instead of the original repo - that way we can delete mutations that are found in more than one constellation.

**Comment by ArtPoon** [comment]
For now, please delete the three mutations from our local copies of the BA.1 and BA.2 constellations and re-run the data to see what the result is @Abayomi-Olabode

**Comment by DBecker7** [comment]
I made a optimization-based version of the Bayesian model I developed before I left the lab. It produces very similar results to the Bayesian model. I added a bootstrap step for the CI, but it could use some tweaking. I took a half hour this morning to make a branch that applies it to the data if you're interested in using it.

I also included a function called "astronomize" in that branch that brings the constellations repo in as a variant matrix (heavily based on your code). If you just want to use that, you can delete any rows that are too similar and then just take the column names to get the sites list.

**Comment by DBecker7** [comment]
ProVoC is not peer-reviewed yet, so no worries if you don't use it right away! I hope the astronomize function helps with deleting mutations via matrix operations rather than maintaining a fork.

**Comment by Abayomi-Olabode** [comment]
Still finding a few case with frequencies slightly higher than 100%. Investigating for reasons why

**Comment by ArtPoon** [comment]
@Abayomi-Olabode - the frequencies do not have to sum exactly to 100% because they are being estimated independently - what do you mean by "slightly higher" exactly?

**Comment by Abayomi-Olabode** [comment]
They 2 samples I looked at so far from Western and Waterloo had a BA.1 + BA.2 frequency of 104.22 and 103.54% respectively

**Comment by ArtPoon** [comment]
Yeah that's certainly within our margin of error.  Again, the frequencies are being estimated independently so there is no constraint on them to sum to 100%.
