### ISSUE TITLE
Errors when running the estimate-freqs script

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/gromstole#55]
1. Processing `waterloo/run21` for BA.1 constellation:
```R
Error in if (zz > -0.001) zz <- max(zz, 0) else stop("profiling has found a better solution, so original fit had not converged") : 
  missing value where TRUE/FALSE needed
Calls: suppressMessages ... tryCatchList -> confint -> confint.glm -> profile -> profile.glm
In addition: Warning message:
In regularize.values(x, y, ties, missing(ties), na.rm = na.rm) :
  collapsing to unique 'x' values
Execution halted
```
Is this related to #43?

2. Processing `guelph/20220319_123730` for BA.2 constellation:

```R
Warning message:
 10 failed to parse. 
Error in family$linkfun(mustart) : 
  Argument mu must be a nonempty numeric vector
Calls: sapply ... glm -> eval -> eval -> glm.fit -> <Anonymous> -> .Call
In addition: There were 11 warnings (use warnings() to see them)
Execution halted
```

**Comment by GopiGugan** [comment]
1. Results are fine for `waterloo/run21` after recent re-run.
2. Error persists for the following runs:
    * `western/K7DTB_16FEB22` - B.1.617.2
    * `guelph/20220301_092257` - BA.1
    * `guelph/20220311_085522` - BA.1
    * `guelph/20220319_123730` - BA.2

**Comment by ArtPoon** [comment]
Ok, I'm stepping through `guelph/20220301_092257` - BA.1 right now.
I reproduced this error:
```
Warning message:
 11 failed to parse. 
```
which was associated with parsing the metadata file.
File contains excessive commas:
```
<U+FEFF>Specimen collector sample ID,host specimen voucher,sample collected by,sample collection date,sample collection time,geolocation name (region),geolocation latitude,geolocation longitude,environmental material,environmental site,collection device,collection protocol,specimen processing,specimen processed by,library preparation kit,library preparation by,library ID,sequencing date,sequencing by,sequencing instrument,flowcell barcode,sequencing protocol name,sequencing kit number,run folder name,raw sequence data process- ing method,r1 fastq filename,r1 SHA-1 checksum,r2 fastq filename,r2 SHA-1 checksum,InterOp file checksum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```

**Comment by ArtPoon** [comment]
Ok, the above error is due to non-compliant date entries like `2022-01-28, 8am` and `Feb 1-2, 2022`.
I think we have no choice but to treat these as missing data.

**Comment by ArtPoon** [comment]
On running the loop containing `fit <- glm(cbind(y, n-y) ~ 1, family='quasibinomial')`:
```R
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: glm.fit: algorithm did not converge
2: glm.fit: algorithm did not converge
```

**Comment by ArtPoon** [comment]
Excessive failed CIs:
```
> estimate
          est  lower.95  upper.95
401 0.9567703 0.0000000 1.0000000
400 0.7254362 0.5188895 0.8813310
398 0.9506514 0.7115341 1.0000000
399 0.9425351 0.0000000 1.0000000
397 0.7384651 0.5497388 0.8811969
396 0.8892517 0.0000000 1.0000000
395 0.8077276 0.0000000 1.0000000
382 0.9131759 0.0000000 1.0000000
381 0.9319650 0.0000000 1.0000000
380 0.9630714 0.0000000 1.0000000
391 0.9710770 0.8398343 1.0000000
387 0.6524297 0.4491627 0.8234283
392 0.7488031 0.5513398 0.8936979
393 0.4740206 0.3779217 0.5714287
394 0.9558622 0.7851536 1.0000000
385 0.8775122 0.0000000 1.0000000
384 0.6599382 0.4816522 0.8117824
383 0.6594126 0.4758152 0.8151520
379 0.5931871 0.4390535 0.7357901
378 0.6765518 0.5037237 0.8216711
377 0.9599484 0.7703024 1.0000000
386 0.6970739 0.0000000 1.0000000
389 0.6883469 0.5043897 0.8388751
388 0.6882689 0.4929908 0.8462011
```

**Comment by ArtPoon** [comment]
For the first sample, the following mutations have high coverage and zero count:
* `aa:orf1a:L3674F`
* `del:11288:9` 
* `+2205.GAGCCAGAA` 
* `aa:S:S371L`

I dug into the `mapped.csv` file and noticed some interesting entries:

```
22204,+22205.GAGCCAGAA,ins:22205:9,0.5157894736842101,95
```
suggests that `+2205.GAGCCAGAA` is mislabeled

```
22672,~22673C,aa:S:S371P,0.9662301860785789,2902
22672,~22673A,aa:S:S371T,0.0006891798759476223,2902
22673,~22674T,aa:S:S371F,0.9979159430357225,2879
```
is a known issue - we should replace S371L in the constellation

```
11282,-11283.9,del:11283:9,0.9067055393585489,3087
```
This seems to be an alternate alignment of `del:11288:9`

`aa:orf1a:L3674F` is only observed at very low frequencies in the samples of this run.

**Comment by GopiGugan** [comment]
> I dug into the `mapped.csv` file and noticed some interesting entries:
> 
> ```
> 22204,+22205.GAGCCAGAA,ins:22205:9,0.5157894736842101,95
> ```
> 
> suggests that `+2205.GAGCCAGAA` is mislabeled

This should have been fixed in commit defb1b15233c27c0bec72ed8933b50e05fa6627f

**Comment by ArtPoon** [comment]
Okay.  It looks like `aa:orf1a:L3674F` is contingent to how an adjacent deletion is mapped:
https://github.com/cov-lineages/pango-designation/issues/367

For the `401` sample I'm looking at, the deletion was mapped to `del:11283:9` instead of `11288`

**Comment by ArtPoon** [comment]
Given these inconsistencies, I'm inclined to drop both `del:11288:9` and `aa:orf1a:L3674F` from our constellation. @GopiGugan

**Comment by ArtPoon** [comment]
Need to rerun these samples with latest constellations.

**Comment by ArtPoon** [comment]
Reproduced this error:
```R
Error in family$linkfun(mustart) : 
  Argument mu must be a nonempty numeric vector
In addition: There were 34 warnings (use warnings() to see them)
```
on gromstole 4480f7332d5e93647235d3ad048d930753793e25 and constellations `47418a56`

**Comment by ArtPoon** [comment]
This is a low coverage sample:
```R
> i
[1] 6
> y
 [1]   NA 2647    1 9097   NA   NA   NA   NA   NA   NA   NA   NA
[13]    0    0   NA   NA   NA   NA 6040   NA
> n
 [1]    0 2655    1 9123    0    0    0    0    0    0    0    0
[13]   30 4532    0    0    0    0 6050    0
```

**Comment by ArtPoon** [comment]
The coefficient estimate is enormous, causing the logit transform to give a `NaN`:
```R
>     fit <- glm(cbind(y, n-y) ~ 1, family='quasibinomial')
> fit$coefficients
(Intercept) 
2.65075e+15 
>     exp(fit$coef) / (1+exp(fit$coef))  # probability
(Intercept) 
        NaN
```

**Comment by ArtPoon** [comment]
Digging into the `mapped.csv` file associated with this sample, it's the same problem that we've encounted in other issues (#57) where an amino acid substitution is caused by two or more nucleotide substitutions in the same codon.  We see two of the mutations at high frequencies, but we do not map the result to `S371L`:
```
22672,~22673C,aa:S:S371P,0.9622395833332987,3840
22673,~22674T,aa:S:S371F,0.9973725696269681,3806
```

**Comment by ArtPoon** [comment]
Again, the short term solution is to drop this mutation from the BA.1 constellation.

**Comment by GopiGugan** [comment]
> 2. Error persists for the following runs:
>    
>    * `western/K7DTB_16FEB22` - B.1.617.2
>    * `guelph/20220301_092257` - BA.1
>    * ~`guelph/20220311_085522` - BA.1~
>    * ~`guelph/20220319_123730` - BA.2~

There's still an error when running `western/K7DTB_16FEB22` for B.1.617.2 constellation:

```R
> counts[i, 1:ncol(cvr)]
    aa:S:T19R aa:S:L452R aa:S:P681R aa:S:D950N aa:orf3a:S26L aa:M:I82T aa:orf7a:V82A aa:orf7a:T120I aa:N:D63G aa:N:R203M aa:N:D377Y
10C         0         NA         NA          0             0        NA            NA             NA      1518         NA         NA

> cvr[i, ]
    aa:S:T19R aa:S:L452R aa:S:P681R aa:S:D950N aa:orf3a:S26L aa:M:I82T aa:orf7a:V82A aa:orf7a:T120I aa:N:D63G aa:N:R203M aa:N:D377Y
10C       270          0          0          1             1         0             0              0      1524          0          0
```

But I believe this issue is only with sample `10C`

**Comment by GopiGugan** [comment]
> Given these inconsistencies, I'm inclined to drop both `del:11288:9` and `aa:orf1a:L3674F` from our constellation. @GopiGugan

@ArtPoon did you want to drop these from just the BA.1 constellation file or from the other files as well? I see `del:11288:9` for example in the BA.2 constellation file as well

**Comment by ArtPoon** [comment]
Yes please remove that deletion from all occurrences in the constellation files

**Comment by ArtPoon** [comment]
Regarding sample 10C - the coverage is so lousy that I'm willing to ignore it as an edge case.  We are picking up `aa:S:T19R` in other samples.

**Comment by GopiGugan** [comment]
Successfully processed all runs without errors

**Comment by GopiGugan** [comment]
`waterloo/run21` - BA.1
```R
Error in if (zz > -0.001) zz <- max(zz, 0) else stop("profiling has found a better solution, so original fit had not converged") : 
  missing value where TRUE/FALSE needed
Calls: suppressMessages ... tryCatchList -> confint -> confint.glm -> profile -> profile.glm
Execution halted
```
`western/KCW4M_20MAY22` - BA.2

```R
Error in family$linkfun(mustart) : 
  Argument mu must be a nonempty numeric vector
Calls: sapply ... glm -> eval -> eval -> glm.fit -> <Anonymous> -> .Call
Execution halted
```

**Comment by ArtPoon** [comment]
Step through the script with the input data files to determine the cause

**Comment by GopiGugan** [comment]
Sample `KN1-1015` causing issue with `waterloo/run21` run:

```R
> counts[i, 1:ncol(cvr)]
         aa:orf1a:K856R T5386G del:6513:3 aa:orf1a:A2710T aa:orf1a:I3758V T13195C C15240T aa:S:A67V aa:S:T95I del:21987:9 del:22194:3 +22205.GAGCCAGAA aa:S:G446S aa:S:G496S aa:S:T547K aa:S:N856K aa:S:L981F aa:M:D3G
KN1-1015             NA     NA         NA              NA              NA      NA      NA        NA        NA          NA          NA               NA          1          1         NA         NA         NA       NA
> cvr[i, ]
         aa:orf1a:K856R T5386G del:6513:3 aa:orf1a:A2710T aa:orf1a:I3758V T13195C C15240T aa:S:A67V aa:S:T95I del:21987:9 del:22194:3 +22205.GAGCCAGAA aa:S:G446S aa:S:G496S aa:S:T547K aa:S:N856K aa:S:L981F aa:M:D3G
KN1-1015              0      0          0               0               0       0       0         0         0           0           0                0          2          2          0          0          0        0
```

Generated results by temporarily ignoring this sample

**Comment by ArtPoon** [comment]
A possible fix is to change our filtering criterion for setting `count` to missing data (`NA`).  Currently we set it to `NA` if coverage at that position is zero.  If we use a slightly more stringent cutoff (say a minimum coverage of 10, below which we set counts to `NA` even if they are non-zero), then that should address this particular edge case.

**Comment by GopiGugan** [comment]
For the `western/KMWT4_05OCT22` run:
```R
Error in strsplit(mapped$label, as.character(mapped$pos)) : 
  non-character argument
Calls: lapply -> FUN -> sapply -> lapply -> strsplit
Execution halted
```

**Comment by GopiGugan** [comment]
One of the samples `mapped.csv` file is empty. Re-running without this sample

**Comment by GopiGugan** [comment]
Same sample `HighlandCreek-08132022` from https://github.com/PoonLab/gromstole/issues/66#issue-1356381811
