### ISSUE TITLE
Empty mapped files

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/gromstole#66]
For the most recent run from western (`KL5D4_26AUG22`):

Running the estimate-freqs.R script:
```R
Error in strsplit(mapped$label, as.character(mapped$pos)) : 
  non-character argument
```

```shell
$ cat HighlandCreek-08132022.mapped.csv 
position,label,mutation,frequency,coverage
```

**Comment by GopiGugan** [comment]
For the `HighlandCreek-08132022` data files:

https://github.com/PoonLab/gromstole/blob/9f70b5e2534afb6a46c10c891dad0c45a82f838d/scripts/minimap2.py#L117-L169

Either:
1. `cigar` is `'*'` so `tokens` is usually empty
2. `tokens` don't have `I` or `D` (for example cigar is`'103S34=14S'`) so `diffs` isn't ever updated

<img width=500 src='https://user-images.githubusercontent.com/35086217/187576400-674319b5-3006-4121-bbd0-7998f80de3d0.png' />

**Comment by ArtPoon** [comment]
Looks like the samples in this run got contaminated / failed to enrich for virus.  Just BLASTing the first few reads for the sample you're looking at, I hit:
* uncultured Bacillus sp.
* uncultured Beta proteobacterium
* other uncultured bacteria
with high confidence.  In these cases, "uncultured" probably means they are predicted bacterial genomes from environmental samples, not grown in lab cultures.  I'll notify the lab.
