### ISSUE TITLE
Make mutation list for BQ.1?

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#68]
This is a descendant lineage of BE.1, which in turn is derived from BA.5  - this will exacerbate existing problems with nested frequency estimates.

**Comment by ArtPoon** [comment]
This is now highest priority

**Comment by ArtPoon** [comment]
* Since the request is for BQ.1.1, let's focus on that lineage.
* According to [this](https://github.com/cov-lineages/pango-designation/issues/993) issue, the defining mutations for BQ.1.1 are Orf1b:Y264H and S:N460K.
* S:N460K is also associated with BA.2.75, so we can't use that.  However these involve different *nucleotide* substitutions.  Frustratingly we have followed the general practice of mapping amino acid substitutions, although we do have information about nucleotide differences.
* `aa:orf1b:Y264H` was observed at a frequency of 12.6% in a recent sample.

**Comment by Abayomi-Olabode** [comment]
Do we go with just one mutation?

**Comment by ArtPoon** [comment]
I’d rather not!

**Comment by Abayomi-Olabode** [comment]
@GopiGugan found Orf1b:N1191S. We are looking into it

**Comment by ArtPoon** [comment]
Thanks!  I'm going to delve into S:N460K as a specific nucleotide substitution.
