### ISSUE TITLE
Need to modify estimate-freqs to use nucleotide substitutions

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#71]
Some important amino acid substitutions are caused by different nucleotide substitutions in different lineages.
See #68

**Comment by ArtPoon** [comment]
We really should be using nucleotide frequencies to estimate lineage frequencies - but people expect amino acid substitution labels

**Comment by ArtPoon** [comment]
This would mean changing constellations

**Comment by ArtPoon** [comment]
@GopiGugan is using cov-spectrum to check which nucleotide substitutions are associated with which AA subs

**Comment by ArtPoon** [comment]
We need to decide on how to incorporate nucleotide-level mutations into the constellations JSON format.
Currently we have mutation entries as:
```json
    "sites": [
      "spike:R346T", 
      "ORF1b:N1191S"
    ],
```

So we can either add a new field:
```json
    "nucleotides": [
        "T22942A",
        "A17039G"
    ],
    "sites": [
      "spike:R346T", 
      "ORF1b:N1191S"
    ],
```
where associations betweeen `nucleotides` and `sites` entries is implied by ordering (i.e., first, second in array)

Or we can expand the `sites` entry:
```json
    "sites": [
      "T22942A": "spike:R346T", 
      "A17039G": "ORF1b:N1191S"
    ],
```
A synonymous mutation could store `null` as the value associated with the nucleotide substitution key.

I'm leaning more towards the second option.
@GopiGugan @Abayomi-Olabode

**Comment by GopiGugan** [comment]
We've currently modified the constellation files to look like the following:
```json
    "sites": [
        {
            "nt": "-11288.9",
            "aa": "del:11288:9"
        },
        {
            "nt": "A11537G",
            "aa": "orf1ab:I3758V"
        },
        {
            "nt": "T13195C",
            "aa": "nuc:T13195C"
        },
    ]
```

Would you prefer one of the two options you suggested instead?

**Comment by ArtPoon** [comment]
why change notation from `-11288.9` to `del:11288:9`?

**Comment by Abayomi-Olabode** [comment]
We code the indels like that just for consistency sake. The goal is to modify the R script to compare the label and mutation columns of our mapped.csv files, in order to differentiate nucleotide substitutions that occur in the same position but result in the same amino acid change.

**Comment by ArtPoon** [comment]
Ok just wondering, thanks

**Comment by ArtPoon** [comment]
How should we incorporate nucleotide-level mutation info into the JSON and CSV outputs?
```json
{
  "counts": [
    {
      "aa:S:R346T": 0,
      "aa:orf1b:N1191S": 1,
      "_row": "H1-1037"
    },
    {
      "aa:S:R346T": 0,
      "aa:orf1b:N1191S": 1,
      "_row": "H1-1036"
    },
...
  "coverage": [
    {
      "aa:S:R346T": 89,
      "aa:orf1b:N1191S": 10128,
      "_row": "H1-1037"
    },
    {
      "aa:S:R346T": 26,
      "aa:orf1b:N1191S": 1675,
      "_row": "H1-1036"
    },
```

and the `mapped.csv` file looks like this:
```
position,label,mutation,frequency,coverage
26269,~26270T,aa:E:T9I,0.9707602339180885,1539
23402,~23403G,aa:S:D614G,0.9899497487437401,3582
```

I propose the following change to the JSON format:
```json
[
  {
    "sample": "H1-1037", 
    "mutation": "aa:S:R346T",
    "nucleotide": "~22599C",
    "count": 0,
    "coverage": 89
  },
  {
    "sample": "H1-1037", 
    "mutation": "aa:orf1b:N1191S",
    "nucleotide": "~17039G",
    "count": 1,
    "coverage": 10128
  },
]
```

and we need to add a nucleotide column to the `mapped.csv` format.
This will require changes to the script converting JSON to CSV.

**Comment by ArtPoon** [comment]
Differences in coverage are being caused by our previous use of the first position in a codon as an approximation of coverage for an amino acid residue - since we are now looking at the nucleotide level mutations, we are going to see some different coverage levels among nucleotides in a codon.

**Comment by ArtPoon** [comment]
Close with PR #76
