### ISSUE TITLE
Revisit BQ.1.1 mutation list

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#73]
From Jenn Knapp (UWaterloo), mutations used by alcov for BQ.1.1:
S:N460K - T22942A
S:K444T - A22893C
ORF1b:Y264H - T14257C
ORF1b:N1191S - A17039G
ORF1a:L3829F - C11750T
ORF1b:M1156I - G16935A
ORF1a:Q556K - C1931A
S:R346T - G22599C
T2954C
C28312T

* Note that we are presently using S:R346T and ORF1b:N1191S.
* We need to drop S:R346T because it is present at substantial frequencies in other lineages, e.g., BA.4.6
* Another possibility is grouping BQ.1 with BQ.1.1

**Comment by Abayomi-Olabode** [comment]
Jenn's mutation are shared with BQ.1, It might be a great idea to lump them together as BQ.1+

**Comment by ArtPoon** [comment]
I agree, we're not even calling BQ.1 - *but* people are specifically interested in BQ.1.1 so those estimates become less informative - so I would rather close #71 before looking at merging lineages

**Comment by Abayomi-Olabode** [comment]
`T22942A` is already on 100.00% proportion in BQ.1 while the proportion of `ORF1b:N1191S` is 31.31%

**Comment by Abayomi-Olabode** [comment]
In BQ.1.1 `T22942A` has a proportion of 100.00%  while `ORF1b:N1191S` has a proportion  of 99.45%

**Comment by ArtPoon** [comment]
Differences in coverage are being caused by our previous use of the first position in a codon as an approximation of coverage for an amino acid residue - since we are now looking at the nucleotide level mutations, we are going to see some different coverage levels among nucleotides in a codon.

**Comment by ArtPoon** [comment]
Closing, please do PR in constellations repo
