### ISSUE TITLE
Need to update mutation lists for several other lineages

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#75]
* [ ] BA.5.2.1
* [ ] BA.5.2
* [ ] BF.7
* [ ] BA.5.1
* [ ] BQ.1 ( expand BQ.1.1 ?)
* [ ] BA.4.6
* [ ] BF.10
* [ ] BF.11
* [ ] XBB (we can't call recombinants easily)

**Comment by ArtPoon** [comment]
@Abayomi-Olabode @GopiGugan - I've written an R script (`unique-mutations.R`) that will process the JSON file generated by our Untitled project to:
1. determine the frequencies of mutations in genomes that belong to some *focus* lineage X
2. generate a barplot of frequencies for those mutations in all other (non-focal) lineages

Example for BA.5.2.1:
<img width="407" alt="Screen Shot 2022-11-27 at 10 47 56 PM" src="https://user-images.githubusercontent.com/1109328/204189973-495ab3e9-0ac3-41db-afba-0390514bc3ae.png">

**Comment by ArtPoon** [comment]
I'll copy my current JSON file to `/data/wastewater` so you don't have to generate it yourself (but you just have to run Untitled `retrieve.py` to do so)

**Comment by ArtPoon** [comment]
Note the above plot is displaying the *mean* mutation frequencies, averaged across other lineages.
If there is a handful of lineages that are fixed for the same mutation, it may still be shown as a low frequency.

**Comment by ArtPoon** [comment]
This might be more useful:
```R
max.freq <- apply(others, 2, function(x) row.names(others)[which.max(x)])
```

**Comment by Abayomi-Olabode** [comment]
Thanks
