### ISSUE TITLE
Lineage removed from usher barcode file

### ISSUE THREAD

**Issue by Abayomi-Olabode** [PoonLab/gromstole#84]
Updated barcode files can't be used to analyze historic data. 

- The barcode files contain information about mutations used to call lineages, which are stored in a lineage file (lin*.tsv). For downstream analysis, we create a summarized JSON file with mutations, count and coverage information associated with each lineage. If the downstream analysis is done after the most recent barcodes file was updated, we run into errors

**Comment by Abayomi-Olabode** [comment]
Proposed solutions includes:

- Store usher barcode files on a daily basis
- Run downstream analysis on historic data using corresponding barcode files

**Comment by GopiGugan** [comment]
We're currently archiving barcode files on a daily basis
