### ISSUE TITLE
Outdir not working

### ISSUE THREAD

**Issue by LauraVP1994** [PoonLab/gromstole#87]
Dear, 

I used your script and I think there is a small bug when using the outdir argument.

You should add something like this in your main to create the folder, otherwise it gives an error, at least in my case
`if not os.path.exists(args.outdir):
       os.makedirs(args.outdir)`

**Comment by ArtPoon** [comment]
Sorry it took me so long to respond to this issue and thanks for pointing this out.

**Comment by GopiGugan** [comment]
Thanks for pointing this out @LauraVP1994. The script has been updated
