### ISSUE TITLE
Summary JSON file did not get generated

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/gromstole#89]
It looks like when there is a file named "Undetermined" in the runs uploads folder, the Freyja summary JSON file does not get generated (e.g. 20240125_122448)

**Comment by GopiGugan** [comment]
```console
Traceback (most recent call last):
  File "/home/gromstole/Wastewater/gromstole/freyja/process.py", line 630, in <module>
    summarize_run_data(args.barcodes, args.update_barcodes, args.freyja_update, run, args.indir, args.outdir, callback=cb.callback)
  File "/home/gromstole/Wastewater/gromstole/freyja/process.py", line 291, in summarize_run_data
    if isnan(date.loc[sample, date.columns.tolist()[0]]):
IndexError: list index out of range
```

**Comment by ArtPoon** [comment]
We might need to add a screen for this to prevent the run from breaking - ignore files that do not have a match in summary JSON file and proceed with the rest.  Send e-mail notification about files that do not match.

**Comment by ArtPoon** [comment]
@GopiGugan to check if this fix has been committed
