### ISSUE TITLE
Empty output files generated by Freyja

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/gromstole#94]
https://github.com/andersen-lab/Freyja/compare/v1.5.0...v1.5.1

* Default solver was changed from `ECOS` to `CLARBEL`
* Running with `CLARBEL` generated the following error:
 ```
module 'cvxpy' has no attribute 'CLARABEL'
Error: Demixing step failed. Returning empty data output
```

* Updated `cvxpy` module from version `1.2.2` to `1.5.2`
* This didn’t resolve the issue:
```
Solver error encountered, most likely due to insufficient sequencing depth.Try running with --depthcutoff.
Error: Demixing step failed. Returning empty data output
```

* Running with the ‘ECOS’ solver generates output files with lineage predictions

**Comment by ArtPoon** [comment]
Let's keep an eye on this, since another user had previously reported similar issues arising from using ECOS

**Comment by ArtPoon** [comment]
We decided to go back to the old solver (ECOS) because the new solver (CLARABEL) was producing empty outputs.  So far the only files for which ECOS failed to yield outputs were two samples that were determined to be poor quality.
